### ISSUE TITLE
Automatically exclude gitignore'd files

### ISSUE THREAD

**Issue by mcandre** [jedmao/eclint#148] opened 2018-11-10 20:11 UTC
Currently, eclint recommends a manual `git ls-files` call, which breaks with `Error: Invalid glob argument` in yargs for large projects, and doesn't work too well in Windows either.

As a workaround, I am invoking `git ls-files -z | xargs -0 -r -n 100 $(npm bin)/eclint checkk`, though this barely only works in POSIX shells. It halts processing after the failing batch of 100 paths. It doesn't work in Command Prompt and so on. And this requires specifically the GNU variant of findutils, rather than, for example, macOS system `find`.

Please use a safe, automatic method to exclude any files ignored by version control from linting, that doesn't depend on the user wrapping eclint in additional, fragile shell calls.

**Comment by jednano** [comment] 2018-11-11 23:02
Duplicate of #128

**Closed as completed by jednano** 2018-11-11 23:02 UTC

**Comment by fpuga** [comment] 2019-06-17 19:09
Just for anyone also looking at this if you have files in your repo with spaces or weird characters the way documented in the README to respect .gitignore file `$ env eclint check $(git ls-files)` will thrown an error. At least in linux/bash.

As @mcandre does, i'm also using this command

```
git ls-files -z | xargs -0 node_modules/.bin/eclint check
```
