### ISSUE TITLE
Better formatting for JavaDocs

### ISSUE THREAD

**Issue by mcandre** [jedmao/eclint#149] opened 2018-11-10 21:38 UTC
By convention, Java API documentation comments don't follow the simple indentation nesting rules, but rather line up each line with the opening indentation + an additional space + an asterisk + a further space + some comment text (optional):

```java
/**
 * Blah
 * Blah
 * Blah
 */
public class ThingAMaBob {}
```

Could we inform eclint to handle `*.java` sources better, so that EditorConfig rules for indentation don't clash with JavaDoc conventions?

As a workaround, I can set the indentation to a single space, but that's not really good.

**Comment by jednano** [comment] 2018-11-11 23:01
Duplicate of #85 and #39.

**Closed as completed by jednano** 2018-11-11 23:01 UTC

**Comment by gucong3000** [comment] 2018-11-19 11:06
```ini
# EditorConfig is awesome: http://EditorConfig.org

# top-most EditorConfig file
root = true

[*]
block_comment_start = /*
block_comment = *
block_comment_end = */
```
